export function getDefaultPhases() {
  return [
    {
      id: "forecast",
      title: "Phase 1 — Forecasting",
      color: "#0F6E56",
      bgColor: "#E1F5EE",
      steps: [
        {
          id: "f1",
          actor: "PCH",
          actorColor: "#D85A30",
          title: "Share forecast",
          detail: "PCH sends demand forecast to CSA TH",
          sections: {
            input: {
              description: "PCH sends the following forecast data",
              dataElements: [
                { name: "Origin country", description: "Always Thailand" },
                { name: "Destination country", description: "Country-level (except where specific port is designated)" },
                { name: "Number of containers", description: "Total container count per destination" },
                { name: "ETD period", description: "Requested departure period (e.g. P3W1)" },
              ],
              frequency: "Once per month, 3 months before ETD",
              source: "PCH team (contact: Hut)",
              escalation: {
                trigger: "If forecast doesn't arrive on schedule",
                level1: { to: "Hut (PCH)", method: "Email", action: "Resend forecast immediately" },
                level2: { to: "Sukumar/KT", method: "Email", action: "Escalate and coordinate resend", timeToLevel2: "2 hours after Level 1" },
              },
            },
            output: {
              description: "CSA TH confirms receipt of the forecast data. No transformation happens at this step — it is purely receive and acknowledge.",
            },
            deliverables: {
              format: "Excel file",
              method: "Email",
              recipient: "CSA TH team inbox (picked up by Mui)",
              confirmation: "Mui sends email confirmation back to Hut acknowledging receipt",
            },
            communication: {
              sender: { actor: "PCH", contact: "Hut" },
              receiver: { actor: "CSA TH", contact: "Mui" },
              confirmationRequired: true,
              confirmationMethod: "Email acknowledgment",
            },
            timeline: {
              frequency: "Once per month",
              relativeToETD: "3 months before ETD",
              additionalConstraints: "None beyond the monthly cadence",
            },
            dependencies: {
              upstream: "None — this is the initiation step of the entire process",
              blockedBy: [],
            },
            slas: {
              frequency: "Once per month",
              maxCompletionTime: null,
              escalationSLAminutes: 240,
              escalationSLADescription: "If not received within expected monthly window, escalate within 4 hours",
            },
            owner: {
              organization: "CSA TH",
              contact: "Mui",
              responsibility: "Receiving and validating forecast data",
            },
            lineage: {
              outputFields: [
                { field: "Origin country", flowsTo: "f2 — match to GOT origin" },
                { field: "Destination country", flowsTo: "f2 — match to GOT destination → determines which lanes apply" },
                { field: "Number of containers", flowsTo: "f3 — input for carrier allocation split calculation" },
                { field: "ETD period", flowsTo: "f2 — match to GOT period/week allocation; f3 — determines which period's allocation ratios to use" },
              ],
            },
          },
          arrow: "right",
        },
        {
          id: "f2",
          actor: "CSA TH",
          actorColor: "#534AB7",
          title: "Match to Cargoo GOT",
          detail: "Map PCH forecast to Cargoo lane structure",
          sections: {
            input: {
              description: "Two data sources feed into this step",
              dataElements: [
                { name: "Origin country (PCH)", description: "Always Thailand" },
                { name: "Destination country (PCH)", description: "Country-level (except where specific port is designated)" },
                { name: "Number of containers (PCH)", description: "Total container count per destination" },
                { name: "ETD period (PCH)", description: "Requested departure period (e.g. P3W1)" },
                { name: "Line ID (Cargoo GOT)", description: "Unique lane identifier" },
                { name: "Origin country (Cargoo)", description: "Thailand" },
                { name: "Destination country (Cargoo)", description: "Matches PCH destination" },
                { name: "Quarterly allocation (Cargoo)", description: "Must be divided by period and week to match PCH forecast granularity" },
                { name: "POR (Place of receipt)", description: "From Cargoo GOT" },
                { name: "FND (Final destination)", description: "From Cargoo GOT" },
                { name: "Requirements per market", description: "Additional input data" },
              ],
              frequency: "Once per month, aligned with PCH forecast cycle",
              source: "PCH forecast (f1) + Cargoo GOT system",
              transformation: "Match origin/destination → extract Line ID–Carrier combinations → count total containers → calculate % share → multiply by PCH forecast to split by Lane ID–Carrier–Period",
              escalation: {
                trigger: "If GOT mapping or period allocation data is unavailable or inconsistent",
                level1: { to: "Mui (CSA TH)", method: "Email", action: "Verify GOT data and resolve mapping inconsistencies" },
                level2: { to: "Victor", method: "Email", action: "Coordinate with Cargoo TMS to correct lane/period allocations", timeToLevel2: "4 hours after Level 1" },
              },
            },
            output: {
              description: "Carrier allocation split with Lane ID–Carrier–Period unique identifier, containing: TEU count, Carrier, Lane ID, Period",
            },
            deliverables: {
              format: "Excel file",
              method: "Email",
              recipient: "Carriers (MSC, Maersk, ONE, OOCL, etc.)",
              confirmation: "Email receipt acknowledgment from lead carrier contact",
            },
            communication: {
              sender: { actor: "CSA TH", contact: "Operations team" },
              receiver: { actor: "Carriers", contact: "Carrier operations contacts" },
              confirmationRequired: true,
              confirmationMethod: "Email acknowledgment from carriers",
            },
            timeline: {
              frequency: "Once per month",
              relativeToETD: "Aligned with monthly forecast cycle from PCH",
              additionalConstraints: "Must be completed within 2 business days of receiving PCH forecast",
            },
            dependencies: {
              upstream: "f1 must be complete — PCH forecast must have been received and confirmed by Mui",
              blockedBy: ["f1"],
            },
            slas: {
              frequency: "Once per month",
              maxCompletionTime: "2 business days after receiving PCH forecast",
              escalationSLAminutes: 480,
              escalationSLADescription: "If not completed within 2 business days, escalate within 8 hours",
            },
            owner: {
              organization: "CSA TH",
              contact: "Operations team (managed by Mui)",
              responsibility: "Matching PCH forecast to Cargoo GOT lanes, calculating allocation splits by carrier and period",
            },
            lineage: {
              outputFields: [
                { field: "Lane ID", flowsTo: "f3 (carrier split calculation), f4 (carrier notification), f5 (forecast dashboard)" },
                { field: "Carrier", flowsTo: "f3 (split ratio), f4 (carrier notification), f5 (dashboard)" },
                { field: "Loading week (Period)", flowsTo: "f3 (period-specific allocation ratio), f5 (dashboard period column)" },
                { field: "Containers (split TEU)", flowsTo: "f3 (allocated container count), f4 (space reservation qty), f5 (allocated containers column)" },
              ],
            },
          },
          arrow: "right",
        },
        {
          id: "f3",
          actor: "CSA TH",
          actorColor: "#534AB7",
          title: "Carrier allocation split",
          detail: "If multiple carriers serve same destination, split by allocation ratio",
          sections: {
            input: { description: "Receiving output from f1 and f2" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "Depends on f1 and f2 completion" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: "right",
        },
        {
          id: "f4",
          actor: "Carriers",
          actorColor: "#378ADD",
          title: "Space reservation",
          detail: "Allocated quantities shared with carriers to reserve vessel space",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: "down",
        },
        {
          id: "f5",
          actor: "CSA TH",
          actorColor: "#534AB7",
          title: "Create forecast dashboard",
          detail: "Dashboard to track forecast → actual progression",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: null,
        },
      ],
    },
    {
      id: "booking",
      title: "Phase 2 — Booking process",
      color: "#534AB7",
      bgColor: "#EEEDFE",
      steps: [
        {
          id: "b1",
          actor: "PCH",
          actorColor: "#D85A30",
          title: "Send booking requests",
          detail: "PCH submits formal booking instructions",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: "right",
        },
        {
          id: "b2",
          actor: "CSA TH",
          actorColor: "#534AB7",
          title: "Transform to Cargoo shipments",
          detail: "Split booking lines into individual shipments",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: "right",
        },
        {
          id: "b3",
          actor: "Cargoo",
          actorColor: "#0F6E56",
          title: "Store shipment data",
          detail: "Record all booking and transport plan data",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: "down",
        },
        {
          id: "b4",
          actor: "CSA TH",
          actorColor: "#534AB7",
          title: "Update booking dashboard",
          detail: "Capture granular booking-level tracking",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: "right",
        },
        {
          id: "b5",
          actor: "System",
          actorColor: "#BA7517",
          title: "Container pool created",
          detail: "Pool of confirmed containers available for PCH SKU planning",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: null,
        },
      ],
    },
    {
      id: "planning",
      title: "Phase 3 — Planning & warehouse execution",
      color: "#BA7517",
      bgColor: "#FAEEDA",
      steps: [
        {
          id: "p1",
          actor: "PCH",
          actorColor: "#D85A30",
          title: "Assign SKUs to containers",
          detail: "PCH selects containers from pool and assigns product",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: "right",
        },
        {
          id: "p2",
          actor: "Cargoo",
          actorColor: "#0F6E56",
          title: "Generate container reference",
          detail: "Cargoo generates the reference — not PCH",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: "right",
        },
        {
          id: "p3",
          actor: "PCH",
          actorColor: "#D85A30",
          title: "Share planning with warehouse",
          detail: "Planning information sent to warehouse for picking",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: "down",
        },
        {
          id: "p4",
          actor: "Warehouse",
          actorColor: "#888780",
          title: "Execute picking",
          detail: "Warehouse performs physical picking and reports status",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: "split",
        },
        {
          id: "p5a",
          actor: "Complete",
          actorColor: "#0F6E56",
          title: "Picking complete",
          detail: "All SKUs picked successfully",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: null,
        },
        {
          id: "p5b",
          actor: "Partial",
          actorColor: "#D85A30",
          title: "Picking partial",
          detail: "Not all SKUs available",
          sections: {
            input: { description: "TBD" },
            output: { description: "TBD" },
            deliverables: { description: "TBD" },
            communication: { description: "TBD" },
            timeline: { description: "TBD" },
            dependencies: { description: "TBD" },
            slas: { description: "TBD" },
            owner: { description: "TBD" },
            lineage: { description: "TBD" },
          },
          arrow: null,
        },
      ],
    },
  ];
}
